language: rust
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt --all -- --write-mode=diff
  - cargo build
  - cargo test -- --test-threads=3
rust:
  - stable

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/249be0ef99ebe40a8a72
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
