[package]
name = "stellar-cli"
version = "0.1.0"
authors = ["Kevin Bacha <chewbacha@gmail.com>"]

[[bin]]
name = "stellar"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4" }
clap = "2.31"
stellar-client = { path = "../client" }
